### ISSUE TITLE
Undefined

### ISSUE THREAD

**Issue by ashtonmths** [arnabsen1729/IPLStats#1]
![Screenshot_2020-10-20-20-53-23-98](https://user-images.githubusercontent.com/68967455/96607848-633bbe00-1316-11eb-84c5-131235087400.jpg)
When i do the live function. i get as undefined instead of the score @arnabsen1729 
![Screenshot (41)](https://user-images.githubusercontent.com/68967455/96608268-cc233600-1316-11eb-8138-94b29ea673f8.png)

**Comment by arnabsen1729** [comment]
It shows that before the game has started and if there was no game before, basically there needs to be one condition to check if the data is not undefined. I noticed it too but was too lazy to work again. Now, since you have mentioned  I will fix it.

**Comment by ashtonmths** [comment]
> It shows that before the game has started and if there was no game before, basically there needs to be one condition to check if the data is not undefined. I noticed it too but was too lazy to work again. Now, since you have mentioned  I will fix it. 

Thank you soo much. But I have tried it when the match was going on i.e DC vs Kxip. BTW thanks for the fast response!!!

**Comment by arnabsen1729** [comment]
Actually the API takes some time to refresh, so you will not get a live data, there is a bit of lag, I haven't found any other suitable API, I can do one thing that is scrape the data from the official website, like the one I did for standings. I will commit the correction tomorrow, since I would like to test it again myself before tomorrow's match. 
Also you can deploy your bot in heroku, I have already deployed mine, so that I can use it 24/7, but the reason I didn't make it public, because the api allows only 100 reqs per days. ;~; Anyways if you need help in deploying the api, Take a look at this [tutorial](https://www.youtube.com/watch?v=f3wsxbMbi5M),if you still have any problem let me know, I will make a doc regarding how I deployed mine. :smile:

**Comment by ashtonmths** [comment]
> Actually the API takes some time to refresh, so you will not get a live data, there is a bit of lag, I haven't found any other suitable API, I can do one thing that is scrape the data from the official website, like the one I did for standings. I will commit the correction tomorrow, since I would like to test it again myself before tomorrow's match. 
> Also you can deploy your bot in heroku, I have already deployed mine, so that I can use it 24/7, but the reason I didn't make it public, because the api allows only 100 reqs per days. ;~; Anyways if you need help in deploying the api, Take a look at this [tutorial](https://www.youtube.com/watch?v=f3wsxbMbi5M),if you still have any problem let me know, I will make a doc regarding how I deployed mine. :smile: 

Yes I have already deployed my bot thank you. And thanks for your hard work!!

**Comment by arnabsen1729** [comment]
Issue Fixed :heavy_check_mark: 
Tested :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/51032928/96685422-b5bebe00-139a-11eb-8763-62d9d52d552e.png)

**Comment by ashtonmths** [comment]
Thank you!!!
